version: '3.9'
services:
  backend:
    build: ./BackEnd
    container_name: BackEnd
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./FrontEnd
    container_name: FrontEnd
    ports:
      - "4200:80"
